name: Hello

on:
  push:

jobs:
  hello:
    runs-on: ${{ matrix.os }}
    steps:
      - run: make --help
      - run: make --version
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
