name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - if: runner.os == 'macOS'
        run: |
          brew install coreutils
          echo "PATH=/usr/local/opt/coreutils/libexec/gnubin:${PATH}" >> "${GITHUB_ENV}"
      - run: uname --help
        continue-on-error: true
      - run: rm --help
        continue-on-error: true
      - run: make remove
        continue-on-error: true
      - run: install --help
        continue-on-error: true
      - run: uname --machine
        continue-on-error: true
      - run: uname --kernel-name
        continue-on-error: true
      - run: uname --kernel-name | tr '[:upper:]' '[:lower:]'
        continue-on-error: true
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
